Added camera_eye virtual frame
upkie/upkie_description pull request #19
Opened 2024-07-29 16:20 UTC by Tordjx

Hi there !
A quick PR to add a camera eye frame which corresponds to the eye of the OAK-D lite camera.
Cheers !

2024-07-29 16:34 UTC, stephane-caron requested changes
Hmm the camera eye location doesn't seem right?

```console
python display_frames.py --only camera_eye --variant camera
```

![image](https://github.com/user-attachments/assets/0bbb8b0b-e347-4a9e-a5a1-e20a1a09fdc9)

2024-07-31 08:17 UTC, Tordjx commented
It appears that when only specifying the inertial part of a link, its frame is displayed as the origin for some reason. A workaround I found was to add a visual box of dimension 0 0 0, and it now looks fine.
![Screenshot from 2024-07-31 10-16-42](https://github.com/user-attachments/assets/e81c75b6-5be1-468b-b540-a7133345cd0b)

2024-07-31 08:25 UTC, stephane-caron commented on xacro/torso.xacro
> +    </link>
Can you keep the same indentation for the diff? (``Files changed`` tab of the PR on GitHub)

2024-07-31 09:17 UTC, stephane-caron approved these changes

2024-07-31 09:17 UTC, merged